services:
  postgres:
    image: postgres:15-alpine
    container_name: hzd-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hzd_info_kiosk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hzd_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - hzd-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hzd_info_kiosk"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: hzd-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hzd.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hzd-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  hzd-network:
    driver: bridge
